new chanegs

diff --git a/.github/workflows/vnet-creation.yaml b/.github/workflows/vnet-creation.yaml
--- a/.github/workflows/vnet-creation.yaml
+++ b/.github/workflows/vnet-creation.yaml
@@ -109,18 +109,30 @@ jobs:
       run: terraform -chdir=${{ inputs.resource_group_name }}/${{ inputs.vnet_name }} init
 
     - name: Terraform Plan
-      run: terraform -chdir=${{ inputs.resource_group_name }}/${{ inputs.vnet_name }} plan -out=planfile ${{ github.event.inputs.action == 'destroy' && '-destroy' || '' }}
+      run: terraform -chdir=${{ inputs.resource_group_name }}/${{ inputs.vnet_name }} plan -out=planfile.out ${{ github.event.inputs.action == 'destroy' && '-destroy' || '' }}
 
     - name: Terraform Apply
+      id: execute
       if: ${{ github.event.inputs.action == 'apply' }}
-      run: terraform -chdir=${{ inputs.resource_group_name }}/${{ inputs.vnet_name }} apply -auto-approve planfile
+      run: terraform -chdir=${{ inputs.resource_group_name }}/${{ inputs.vnet_name }} apply -auto-approve planfile.out
 
     - name: Terraform Destroy
       if: ${{ github.event.inputs.action == 'destroy' }}
-      run: terraform -chdir=${{ inputs.resource_group_name }}/${{ inputs.vnet_name }} apply -auto-approve planfile
+      run: terraform -chdir=${{ inputs.resource_group_name }}/${{ inputs.vnet_name }} apply -auto-approve planfile.out
 
     - name: List files
       run: ls -lat
+
+    - name: Check Execute Status
+      id: check_execute_status
+      run: |
+        if [[ "${{ steps.execute.outcome }}" == "success" ]]; then
+          echo "execute success"
+          echo "::set-output name=success::true"
+        else
+          echo "execute failed"
+          echo "::set-output name=success::false"
+        fi
 
     - name: Token generator
       uses: githubofkrishnadhas/github-access-using-githubapp@v2
@@ -143,3 +155,71 @@ jobs:
         git commit -m "Update configuration file for ${{ inputs.resource_group_name }}/${{ inputs.vnet_name }}"
         git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/devwithkrishna/azure-virtual-network-creation-repo.git
         git push
+  verify-vnet:
+    runs-on: ubuntu-latest
+    needs: create-vnet
+    if: needs.create-vnet.outputs.execute_status == 'true'
+
+    steps:
+
+    - name: Proceed with Job 2
+      run: echo "create-vnet 'execute' step was successful, proceeding with verify-vnet."
+
+    - uses: azure/login@v2
+      with:
+        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
+
+    - name: Azure CLI script
+      uses: azure/cli@v2
+      with:
+        azcliversion: latest
+        inlineScript: |
+          az account show
+          # Check if VNet exists
+          echo "Checking if VNet exists..."
+          output=$(az network vnet show -g MyResourceGroup -n MyVNet 2>/dev/null)
+
+          if echo "$output" | jq empty > /dev/null 2>&1; then
+            echo "VNet exists. Command succeeded."
+          else
+            echo "VNet does not exist or the command failed."
+            exit 1
+          fi
+
+    - name: Execute only if VNet exists
+      if: ${{ success() }}
+      run: |
+        echo "The VNet exists. Proceeding with the next step."
+        echo "Preparing Helpdesk email...."
+
+    - uses: actions/setup-python@v5
+      with:
+        python-version: '3.12'
+
+    - name: Install pipenv
+      run: |
+        pip install pipenv 
+        pipenv install --skip-lock
+
+    - name: Get Actor Email
+      run: |
+        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            -H "Accept: application/vnd.github+json" \
+            https://api.github.com/users/${{ github.actor }} > user.json
+
+        USER_EMAIL=$(jq -r '.email // ""' user.json)
+        if [ -z "$USER_EMAIL" ]; then
+          echo "The user email is not publicly available."
+          USER_EMAIL="no-reply@example.com" # Fallback email if not available
+        fi
+
+        echo "USER_EMAIL=$USER_EMAIL" >> $GITHUB_ENV
+
+    - name: prepare email for Helpdesk team
+      run: |
+        pipenv run python3 send_email.py --application_name "${{ inputs.application_name }}" \
+                  --environment "${{ inputs.environment }}" \
+                  --region "${{ inputs.location }}" \
+                  --vnet_name "${{ inputs.vnet_name }}" \
+                  --address_space "${{ inputs.vnet_address_space }}" \
+                  --subscription_id "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
